### PR TITLE
Identify GM\d layers as outline, GKO is keep-out

### PR DESCRIPTION
**Pull request by kasbah**
http://tinymicros.com/wiki/Protel_Gerber_Layer_Names

Based on working with these gerbers: https://github.com/OculusVR/RiftDK1/tree/master/Schematics/Gerbers

### CODE REVIEW

**Comment by mcous** [comment]
Thanks for the PR! I see you replaced `.gko` with `.gmX`, but `.gko` should definitely remain detected as an outline layer. I know technically it is "keep-out", but it is often used in real-life as an outline (see http://docs.oshpark.com/submitting-orders/naming-pattern/).

Also, can you add a test for GMx as an outline?

Finally, since you've already gone and done a PR for layer detection, it would be awesome if you could throw a fix for #5, as well.

**Comment by kasbah** [comment]
Done, could add a test for `.drd` as well but it all seems a bit cumbersome test code for some simple regexps.

**Comment by mcous** [comment]
I'd like a test in place to guard against any regressions, even for the simple stuff. I just started a big refactor for the next release of gerber-to-svg

**Comment by kasbah** [comment]
Ok, that actually made me catch some issues too. 

I have now also changed `.drd` from outline to drill and used `fab` for the OrCad test as that is my best guess since I found this: http://bdml.stanford.edu/twiki/bin/view/Rise/CadencePCBTutorial.html

**Comment by mcous** [comment]
:+1:

**Comment by mcous** [comment]
Released as v0.0.4

**Pull request merged**
