### PR TITLE
Add openhardware.io

### PR DESCRIPTION
**Pull request by henrikekblad**

### CODE REVIEW

**Comment by kasbah** [comment]
Cool that you are using this too! 

I should probably stay out of it since I am running a sort of competing project but maybe less sales-pitchey tone would be better? 

> A social site around open source hardware. Enables authors to sell and manufacture their boards.

I'll let @mcous decide anyway.

**Comment by mcous** [comment]
Thanks for the PR! I'm gonna echo what @kasbah said here and ask that we go for a more neutral tone

**Comment by henrikekblad** [comment]
Haha, help me guys, what should we say then :)

**Comment by kasbah** [comment]
I put something in quotes above. 
>A social site around open source hardware. Enables authors to sell and manufacture their boards.

**Comment by henrikekblad** [comment]
Oh.. missed that one. I'll update the PR, just a sec.

**Comment by henrikekblad** [comment]
@kasbah, Just saw you work on kitnic, 👍 

Just love to see more people wanting to make open source hardware more accessible!

**Comment by kasbah** [comment]
Right back at you, I first saw openhardware.io a while ago, you have been making some great progress!

**Comment by henrikekblad** [comment]
Would be fun to continue a discussion with you. But maybe better to do it this PR.

**Comment by kasbah** [comment]
Sure, send me an email or jump on https://gitter.im/monostable/kitnic. 

We are duplicating some effort with our projects I guess, but I suppose it's the right way to find out what people want. Do you agree?

**Pull request merged**
